### ISSUE TITLE
64bit Counter for NewTotalBytesSent NewTotalBytesReceived

### ISSUE THREAD

**Issue by dinuxdotde** [GAS85/fritzboxpoller#1]
Hello,
i think its better to use the "new" 64bit keywords to query the traffic.

According to this document, Site 2, [https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/IGD1.pdf](url), 
AVM  indroduced a new Keyword for 64bit Counter.

Can you please replace:
  **NewTotalBytesSent** with **NeWX_AVM_DE_TotalBytesSent64**
and
  **NewTotalBytesReceived** with **NeWX_AVM_DE_TotalBytesReceived64**
in your Script.

Kind regards,
Oliver

**Comment by GAS85** [comment]
Hmm, seems `NeWX_AVM_DE_TotalBytesSent64` was introduced in 2017 and only difference to `NewTotalBytesSent` is that it is permanent and will never be reset. It also different kind of config in Cacti, ether you expect *gauge* or *counter*. I would rather think to add option and user can select if he would like to use one or another. What you think?

**Comment by dinuxdotde** [comment]
> Hmm, seems `NeWX_AVM_DE_TotalBytesSent64` was introduced in 2017 and only difference to `NewTotalBytesSent` is that it is permanent and will never be reset. It also different kind of config in Cacti, ether you expect _gauge_ or _counter_. I would rather think to add option and user can select if he would like to use one or another. What you think?

Ok, i use the new  one with "counter" as Data-Source-Type. But why is the expect type different? Both give total bytes send/received from interface.

**Comment by GAS85** [comment]
Ok, I add it as option it anybody would like to use old one. Check if out: https://github.com/GAS85/fritzboxpoller/pull/3
If it fits, I will merge it.
