### ISSUE TITLE
Add Option to set FritzBoxAddr as variable

### ISSUE THREAD

**Issue by dinuxdotde** [GAS85/fritzboxpoller#2]
It would be nice, to add a switch to set the FritzBoxAddr via options in Case of multiple FritzBoxes.

Ex.
-d = Device-IP

fritzbox.sh -d 192.168.155.1

This should overwrite the "hard coded" variable FritzBoxAddr="192.168.0.1".

Kind regards,
Oliver

**Comment by GAS85** [comment]
Actually this is a good idea, check this out.
But I do not know when you can have few fritzboxes in the network :thinking:

**Comment by dinuxdotde** [comment]
> Actually this is a good idea, check this out. But I do not know when you can have few fritzboxes in the network 🤔

yes, if you have a Mesh for WLAN/DECT/VoIP connected via Ethernet-Cable
